// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Company
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faCompanyAccess from '@/i18n/company-access/fa.json';
import enCompanyAccess from '@/i18n/company-access/en.json';
import faCompanyAccessGuide from '@/i18n/company-access-guide/fa.json';
import enCompanyAccessGuide from '@/i18n/company-access-guide/en.json';
import faCompanyCreateGuide from '@/i18n/company-create-guide/fa.json';
import enCompanyCreateGuide from '@/i18n/company-create-guide/en.json';
import faCompanyDocument from '@/i18n/company-document/fa.json';
import enCompanyDocument from '@/i18n/company-document/en.json';
import faCompanyInformation from '@/i18n/company-information/fa.json';
import enCompanyInformation from '@/i18n/company-information/en.json';
import faCompanyInformationGuide from '@/i18n/company-information-guide/fa.json';
import enCompanyInformationGuide from '@/i18n/company-information-guide/en.json';
import faCompanyViewGuide from '@/i18n/company-view-guide/fa.json';
import enCompanyViewGuide from '@/i18n/company-view-guide/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'company-access': faCompanyAccess,
  'company-access-guide': faCompanyAccessGuide,
  'company-create-guide': faCompanyCreateGuide,
  'company-document': faCompanyDocument,
  'company-information': faCompanyInformation,
  'company-information-guide': faCompanyInformationGuide,
  'company-view-guide': faCompanyViewGuide,
  },
  en: {
  'company-access': enCompanyAccess,
  'company-access-guide': enCompanyAccessGuide,
  'company-create-guide': enCompanyCreateGuide,
  'company-document': enCompanyDocument,
  'company-information': enCompanyInformation,
  'company-information-guide': enCompanyInformationGuide,
  'company-view-guide': enCompanyViewGuide,
  },
} as const;
